#these params havent used now!!
color_image_topic: "/camera/rgb/image_raw"
depth_image_topic: "/camera/aligned_depth_to_color/image_raw"
odom_topic: ""
circle_pose_topic: "/mas/drone_1/circle_pose"

camera_type: 'RGBD'   #MONO , STEREO , RGBD
detect_method: 'DEPTH'  #DEPTH , COLOR

#D435i
color_fx: 605.72
color_fy: 606.08
color_cx: 326.62
color_cy: 247.01

#D435i aligned depth
depth_fx: 605.72
depth_fy: 606.08
depth_cx: 326.62
depth_cy: 247.01

real_circle_radius_big: 1.02
real_circle_radius_small: 0.80

color_width: 640
color_height: 480

depth_width: 640
depth_height: 480

resize_depth: false #default enlarge 2 times
show_image: true

#RANSAC
use_RANSAC: true
iter_time: 350
least_error: 0.10
least_circle_ratio: 0.7

#for detecting circle
min_contours_area: 2000.0
min_points_in_camera: 150 #if point num < 100 , then consider this points is not enough to fit circle

pixel_move: 8   #choose the points in the circle , not in the circle's edge
pixel_move_max: 20